// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Item struct {
	ID    int32  `json:"id"`
	Name  string `json:"name"`
	Price int32  `json:"price"`
}

type Purchase struct {
	ID           int32            `json:"id"`
	BuyerID      pgtype.Int4      `json:"buyer_id"`
	ItemID       pgtype.Int4      `json:"item_id"`
	Quantity     int32            `json:"quantity"`
	TotalCost    int32            `json:"total_cost"`
	PurchaseDate pgtype.Timestamp `json:"purchase_date"`
}

type Transaction struct {
	ID         int32            `json:"id"`
	SenderID   pgtype.Int4      `json:"sender_id"`
	ReceiverID pgtype.Int4      `json:"receiver_id"`
	Amount     int32            `json:"amount"`
	Timestamp  pgtype.Timestamp `json:"timestamp"`
}

type User struct {
	ID           int32            `json:"id"`
	Username     string           `json:"username"`
	PasswordHash string           `json:"password_hash"`
	Balance      pgtype.Int4      `json:"balance"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}
