// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateItem(ctx context.Context, arg CreateItemParams) (Item, error)
	CreatePurchase(ctx context.Context, arg CreatePurchaseParams) (Purchase, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transaction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetCurrentBalance(ctx context.Context, id int32) (pgtype.Int4, error)
	GetItemByID(ctx context.Context, id int32) (Item, error)
	GetItemByName(ctx context.Context, name string) (Item, error)
	GetPurchases(ctx context.Context, buyerID pgtype.Int4) ([]GetPurchasesRow, error)
	GetTransactions(ctx context.Context, senderID pgtype.Int4) ([]GetTransactionsRow, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error)
	UpdateBalanceForPurchase(ctx context.Context, arg UpdateBalanceForPurchaseParams) error
	UpdateBalanceForTransfer(ctx context.Context, arg UpdateBalanceForTransferParams) error
}

var _ Querier = (*Queries)(nil)
